# Please take note of the inline directives.
# Make changes only between the specified section
# Upstream image is CentOS 7

# Change the source image, if necessary
FROM ${NUXEO_IMAGE}

# !!! DO NOT CHANGE BELOW THIS LINE !!!

ARG NUXEO_CLID
ENV NUXEO_CLID ${XVAR}NUXEO_CLID
ARG INSTALL_RPM
ENV INSTALL_RPM ${XVAR}INSTALL_RPM

# We need to be root to run yum commands
USER 0

# Set UTF8 default locale
ENV LANG="en_US.UTF-8" \
    LANGUAGE="en_US:en" \
    LC_ALL="en_US.UTF-8"

# Create out of place stream directory
ENV NUXEO_HOME /opt/nuxeo/server
RUN mkdir -p ${XVAR}NUXEO_HOME/stream \
  && chown 900:0 ${XVAR}NUXEO_HOME/stream && chmod g+rwX ${XVAR}NUXEO_HOME/stream

# Install RPM Fusion free repository
RUN yum -y localinstall --nogpgcheck https://mirrors.rpmfusion.org/free/el/rpmfusion-free-release-7.noarch.rpm \
    && rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-el-7 \
    && yum -y install ffmpeg mediainfo x264 x265 ipa-mincho-fonts

# Dependencies for GLB thumbnail generation
#RUN yum -y install alsa-lib at-spi2-atk libX11 libXcomposite libXcursor libXdamage libXext libXi libXtst libXScrnSaver libXrandr libXrandr atk pango gtk3

# Add additional RPMs to the source image
RUN if [ -n "${XVAR}{INSTALL_RPM}" ]; then yum -y install ${XVAR}{INSTALL_RPM}; fi

# !!! DO NOT CHANGE ABOVE THIS LINE !!!

# >>> Make your changes BELOW this line <<<

# See: https://github.com/nuxeo/nuxeo/tree/master/docker for source documentation

# Example custom package installation
# COPY --chown=900:0 /docker-entrypoint-initnuxeo.d/local-package-nodeps-*.zip ${XVAR}NUXEO_HOME/local-packages/local-package-nodeps.zip
# COPY --chown=900:0 /docker-entrypoint-initnuxeo.d/local-package-*.zip ${XVAR}NUXEO_HOME/local-packages/local-package.zip

# Install a local package without its dependencies (`mp-install --nodeps`)
# RUN /install-packages.sh --offline ${XVAR}NUXEO_HOME/local-packages/local-package-nodeps.zip
# Install remote packages and a local package with its dependencies
# RUN /install-packages.sh --clid ${XVAR}{NUXEO_CLID} nuxeo-web-ui nuxeo-drive ${XVAR}NUXEO_HOME/local-packages/local-package.zip

RUN usermod -aG 998 nuxeo

# >>> Make your changes ABOVE this line <<<

# !!! DO NOT CHANGE BELOW THIS LINE (except for noted items) !!!
# Set back original (nuxeo) user
USER 900

# (Optional) Include the google credentials.
# Replace the filename with your value
# COPY google-credential.json /opt/nuxeo/google-credential.json
# ENV GOOGLE_CREDENTIALS_PATH=/opt/nuxeo/google-credential.json

# install node.js and screenshot-glb
#RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash && \
#    source ~/.bash_profile && nvm install 16.13.0 && npm install -g @shopify/screenshot-glb

# workaround to make the screenshot-glb command available in the default system PATH used by Java
#USER 0
#RUN ln -s /home/nuxeo/.nvm/versions/node/v16.13.0/bin/node /usr/local/bin/node
#RUN ln -s /home/nuxeo/.nvm/versions/node/v16.13.0/bin/screenshot-glb /usr/local/bin/screenshot-glb
#USER 900

# !!! END OF FILE !!!