services:
  nuxeo:
    build:
      context: .
      dockerfile: build_nuxeo/Dockerfile
      args:
        - "INSTALL_RPM=${INSTALL_RPM}"
        - "CONNECT_URL=${CONNECT_URL}"
        - "NUXEO_CLID=${NUXEO_CLID}"
        - "BUILD_PACKAGES=${BUILD_PACKAGES}"
        - "NUXEO_IMAGE=${NUXEO_IMAGE}"
    env_file:
      - ./.env
    image: presales-nuxeo-${PROJECT_NAME}
    hostname: nuxeo
    restart: unless-stopped
    depends_on:
      - mongo
      - opensearch
    expose:
      # Webservice Port
      - 8080
      # Port for Debugging (JPDA)
      - 8787
      # JMX port
      - 1089
    ports:
      - "${NUXEO_PORT}:8080"
      - "8787:8787"
      - "1089:1089"
    volumes:
      - ./init:/docker-entrypoint-initnuxeo.d/:rw
      - ./conf:/etc/nuxeo/conf.d/:ro
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /usr/bin/docker:/usr/bin/docker:ro
      - nuxeo-data:/var/lib/nuxeo:rw
      # Makes things pretty slow, uncomment with caution; useful for debugging
      # - ./nuxeo_war:/opt/nuxeo/server/nxserver/nuxeo.war:rw
  mongo:
    image: mongo:${MONGO_VERSION}
    hostname: mongo
    restart: unless-stopped
    healthcheck:
      test: echo 'db.stats().ok' | mongo mongo:27017/test --quiet
      interval: 1m
      timeout: 30s
      retries: 10
      start_period: 15s
    expose:
      # Mongo connection
      - 27017
    # Uncomment the following block if you require host-level access to MongoDB
    #ports:
    #  - "27017:27017"
    volumes:
      - mongo-data:/data/db
  opensearch:
    build:
      context: .
      dockerfile: build_opensearch/Dockerfile
      args:
        - "OPENSEARCH_IMAGE=${OPENSEARCH_IMAGE}"
    env_file:
      - ./.env
    image: presales-opensearch-${PROJECT_NAME}
    hostname: opensearch
    restart: unless-stopped
    healthcheck:
      test: curl -f http://opensearch:9200/
      interval: 2m
      timeout: 30s
      retries: 10
      start_period: 1m
    environment:
      - discovery.type=single-node
      - cluster.name=opensearch
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_SECURITY_PLUGIN=true"
    expose:
      - 9200
      - 9300
    # Uncomment the following block if you require host-level access to ElasticSearch
    #ports:
    #  - 9200:9200
    #  - 9300:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch-data:/usr/share/opensearch/data
  dashboards:
    image: ${OPENSEARCH_DASHBOARDS_IMAGE}
    hostname: dashboards
    restart: unless-stopped
    healthcheck:
      test: curl -f http://dashboards:5601/dashboards
      interval: 2m
      timeout: 30s
      retries: 10
      start_period: 2m
    depends_on:
      - opensearch
    environment:
      OPENSEARCH_HOSTS: http://opensearch:9200/
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: 'true'
      SERVER_BASEPATH: /dashboards
      SERVER_REWRITEBASEPATH: 'true'
    expose:
      - 5601
    ports:
      - "5601:5601"
volumes:
  nuxeo-data:
  opensearch-data:
  mongo-data:
