version: '3.6'
services:
  nuxeo:
    image: nuxeo:${NUXEO_VERSION}
    hostname: ${APPLICATION_NAME}
    depends_on: 
      - mongo
      - elasticsearch
      - elasticsearch2
      - elasticsearch3
    ports:
      - "${NUXEO_PORT}:8080"
    environment:
      - NUXEO_HOSTNAME=${NUXEO_HOSTNAME}
      - NUXEO_PORT=${NUXEO_PORT}
      - NUXEO_PROJECT=${APPLICATION_NAME}
      - NUXEO_PACKAGES=${NUXEO_PACKAGES}
      - NUXEO_TEMPLATES=${NUXEO_TEMPLATES}
      - NUXEO_INSTALL_HOTFIX=${NUXEO_INSTALL_HOTFIX}
      - NUXEO_MPINSTALL_OPTIONS=${NUXEO_MPINSTALL_OPTIONS}
      - NUXEO_DATA=${NUXEO_DATA}
      - NUXEO_LOG=${NUXEO_LOG}
      - NUXEO_USER=${NUXEO_USER}
      - STUDIO_USERNAME=${STUDIO_USERNAME}
      - STUDIO_CREDENTIALS=${STUDIO_CREDENTIALS}
# See: https://hub.docker.com/r/alpine/socat/ to set up docker forwarding
# - Example configuration socat/docker-compose.yml
#      - DOCKER_HOST=tcp://laptop:2376
    volumes:
      - ./init:/docker-entrypoint-initnuxeo.d/:rw
# Mount docker binary to access REST API for blender, etc.
#      - /usr/local/bin/docker:/usr/bin/docker:ro
      - nuxeo-data:/var/lib/nuxeo/data:rw
  mongo:
    image: mongo
    hostname: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.0
    hostname: elasticsearch
    environment:
      - node.name=es01
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    cap_add:
      - ALL
    privileged: true
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.0
    hostname: elasticsearch2
    environment:
      - node.name=es02
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    cap_add:
      - ALL
    privileged: true
    volumes:
      - esdata2:/usr/share/elasticsearch/data
  elasticsearch3:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.0
    hostname: elasticsearch3
    environment:
      - node.name=es03
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    cap_add:
      - ALL
    privileged: true
    volumes:
      - esdata3:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.5.0
    hostname: kibana
    depends_on: 
      - elasticsearch
      - elasticsearch2
      - elasticsearch3    
    environment:
      SERVER_NAME: localhost
      ELASTICSEARCH_URL: http://elasticsearch:9200/
    ports:
      - 5601:5601
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    cap_add:
      - ALL

volumes:
  esdata1:
  esdata2:
  esdata3:
  nuxeo-data:
  mongo-data:
