version: '3.6'
services:
  nuxeo:
    image: ${NUXEO_REGISTRY}/${NUXEO_IMAGE}:${NUXEO_VERSION}
    hostname: nuxeo
    restart: always
    depends_on: 
      - mongo
      - elasticsearch
    ports:
      - "${NUXEO_PORT}:8080"
    env_file:
      - ./env
      - /var/lib/nuxeo/env
# See: https://hub.docker.com/r/alpine/socat/ to set up docker forwarding
# - Example configuration socat/docker-compose.yml
#      - DOCKER_HOST=tcp://laptop:2376
    volumes:
      - ./init:/docker-entrypoint-initnuxeo.d/:rw
      - /usr/bin/docker:/usr/bin/docker:ro
      - nuxeo-data:/var/lib/nuxeo/data:rw
  mongo:
    image: mongo
    hostname: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.0
    hostname: elasticsearch
    restart: always
    environment:
      - node.name=es01
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    cap_add:
      - ALL
    privileged: true
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.5.0
    hostname: kibana
    restart: always
    depends_on: 
      - elasticsearch
    environment:
      SERVER_NAME: localhost
      ELASTICSEARCH_URL: http://elasticsearch:9200/
      SERVER_BASEPATH: /kibana
    ports:
      - "5601:5601"
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    cap_add:
      - ALL

volumes:
  es-data:
  nuxeo-data:
  mongo-data:
