# OpenSearch 2.x
nuxeo.opensearch2.client.server=http://opensearch:9200
nuxeo.search.client.default.opensearch2.settings.numberOfShards=1
nuxeo.search.client.default.opensearch2.settings.numberOfReplicas=0

# MongoDB
nuxeo.mongodb.server=mongo:27017

org.nuxeo.connect.url=https://connect.nuxeo.com/nuxeo/site/

